/* Generated by tools/make-service-worker.py — do not edit by hand.
 *
 * Offline support for Penguin Pebbling. The whole site is about 670 KB, so it is
 * all held except the PDFs, which are cached when someone opens one.
 *
 * Documents, CSS and JS are network-first on purpose. `_headers` revalidates
 * them on every request because a stale stylesheet against fresh markup renders
 * the page wrong — see commit 15bc1bd, which exists because that happened. A
 * cache-first worker would make that permanent instead of lasting a day, and
 * being stuck on an old version is the usual way a service worker hurts a site.
 * The cache is the fallback here, never the source.
 */
const VERSION = "74bc6d582285";
const CACHE = "penguin-pebbling-" + VERSION;

const PRECACHE = [
  "/",
  "/about",
  "/about.html",
  "/changelog",
  "/changelog.html",
  "/how-to-play",
  "/how-to-play.html",
  "/index.html",
  "/locutions",
  "/locutions.html",
  "/print",
  "/print.html",
  "/privacy",
  "/privacy.html",
  "/404.html",
  "/apple-touch-icon.png",
  "/cards/art/deep-pressure.webp",
  "/cards/art/infodumping.webp",
  "/cards/art/parallel-play.webp",
  "/cards/art/penguin-pebbling.webp",
  "/cards/art/support-swapping.webp",
  "/cards/deep-pressure-locution.webp",
  "/cards/infodumping-locution.webp",
  "/cards/parallel-play-locution.webp",
  "/cards/penguin-pebbling-locution.webp",
  "/cards/support-swapping-locution.webp",
  "/favicon.ico",
  "/favicon.svg",
  "/fonts/atkinson-hyperlegible-next-italic-latin-ext.woff2",
  "/fonts/atkinson-hyperlegible-next-italic-latin.woff2",
  "/fonts/atkinson-hyperlegible-next-roman-latin-ext.woff2",
  "/fonts/atkinson-hyperlegible-next-roman-latin.woff2",
  "/icon-maskable.png",
  "/llms.txt",
  "/penguin-pebbling.css",
  "/penguin-pebbling.js",
  "/search-index.json",
  "/site.webmanifest",
  "/theme.js",
];

/* Cache-first: these only change when their generator runs, and when they do the
 * cache name changes with them. */
const IMMUTABLE = /^\/(fonts\/|cards\/|favicon|apple-touch-icon|icon-maskable)/;

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* Individually, not addAll: addAll is atomic, so one URL that 404s on a dev
     * server without clean URLs would abort the install and leave the site with
     * no worker at all. A missing entry just falls through to the network. */
    await Promise.allSettled(PRECACHE.map((url) => cache.add(url)));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((n) => n.startsWith("penguin-pebbling-") && n !== CACHE)
      .map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

async function networkFirst(request) {
  const cache = await caches.open(CACHE);
  try {
    const fresh = await fetch(request);
    if (fresh && fresh.ok) cache.put(request, fresh.clone());
    return fresh;
  } catch (err) {
    const hit = await cache.match(request);
    if (hit) return hit;
    throw err;
  }
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(request);
  if (hit) return hit;
  const fresh = await fetch(request);
  if (fresh && fresh.ok) cache.put(request, fresh.clone());
  return fresh;
}

const OFFLINE_BODY = `<!doctype html><html lang="en-GB"><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Offline \u2014 Penguin Pebbling</title>
<link rel="stylesheet" href="/penguin-pebbling.css">
<div class="wrap"><main class="prose" style="padding-block:3rem">
<h1>This part needs a connection</h1>
<p>The game, the rules, the five locutions and the printable page all work
offline. This particular thing was not saved to your device \u2014 the PDF guides are
only kept once you have opened them.</p>
<p><a href="/">Back to the game</a></p>
</main></div>`;

function offline() {
  return new Response(OFFLINE_BODY, {
    status: 503,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  /* A PDF link has no download attribute, so opening one is a navigation and
   * lands here. Online it is fetched and kept; offline, and not already kept,
   * the reader gets a sentence rather than the browser's error page. */
  if (request.mode === "navigate") {
    event.respondWith(networkFirst(request).catch(async () => {
      const cache = await caches.open(CACHE);
      return (await cache.match(request))
        || (await cache.match("/404.html"))
        || offline();
    }));
    return;
  }

  if (IMMUTABLE.test(url.pathname)) {
    event.respondWith(cacheFirst(request).catch(() => offline()));
    return;
  }

  event.respondWith(networkFirst(request).catch(() => offline()));
});
